name : LMS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install dependencies
        run: go mod tidy

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.62.2
          args: --timeout=5m

      - name: Run tests
        run: go test -v ./...

      - name: Build Application
        run: go build -o lms